volumes:
  dados:

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Diretório de Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql